import { ApplicationConfig, inject, provideBrowserGlobalErrorListeners, provideAppInitializer } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';
import {
  provideTablerIcons,
  IconHome,
  IconDatabase,
  IconMessages,
  IconUsers,
  IconHelpCircle,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconArrowsRightLeft,
  IconBell,
  IconInfoCircle,
  IconTerminal2,
  IconAlertTriangle,
  IconSparkles,
  IconThumbUp,
  IconThumbDown,
  IconArrowUp,
  IconArrowDown,
  IconArrowLeft,
  IconChevronRight,
  IconChevronLeft,
  IconChevronDown,
  IconCalendarMonth,
  IconBuilding,
  IconWorld,
  IconCheck,
  IconAffiliate,
  IconHourglass,
  IconTrendingUp,
  IconTrendingDown,
  IconRobot,
  IconSearch,
  IconTarget,
  IconDownload,
  IconRefresh,
  IconTag,
  IconDotsVertical,
  IconArrowDownRight,
  IconMessageReport,
  IconMessageCheck,
  IconUsersGroup,
  IconUser,
  IconBook2,
  IconArrowsMove,
  IconPlus,
  IconMinus,
  IconLibrary,
  IconChartBar,
  IconFlag,
  IconMap,
  IconFileText,
  IconReport,
  IconBriefcase,
  IconPackage,
  IconStar,
  IconStack2,
  IconChartPie,
  IconChartLine,
  IconCopy,
  IconFileExport,
  IconBulb,
  IconHandClick,
  IconCategory,
  IconX,
  IconMaximize,
  IconMessageCircle2,
  IconFileDownload,
  IconPaperclip,
  IconTriangleFilled,
  IconCircleCheck,
  IconCircleX,
  IconLanguage,
  IconLayoutGrid,
  IconArrowsShuffle,
} from '@tabler/icons-angular';
import {
  MSAL_GUARD_CONFIG,
  MSAL_INSTANCE,
  MSAL_INTERCEPTOR_CONFIG,
  MsalBroadcastService,
  MsalGuard,
  MsalInterceptor,
  MsalService,
} from '@azure/msal-angular';
import {
  msalGuardConfigFactory,
  msalInstanceFactory,
  msalInterceptorConfigFactory,
} from './core/auth/auth.config';
import { provideHttpClient, withFetch, withInterceptorsFromDi, HTTP_INTERCEPTORS } from '@angular/common/http';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { firstValueFrom } from 'rxjs';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideAnimationsAsync(),
    provideHttpClient(withFetch(),withInterceptorsFromDi()),
    provideRouter(routes),
    provideAppInitializer(() => {
      const msalService = inject(MsalService);
      return firstValueFrom(msalService.initialize());
    }),
    { provide: MSAL_INSTANCE, useFactory: msalInstanceFactory },
    { provide: MSAL_GUARD_CONFIG, useFactory: msalGuardConfigFactory },
    { provide: MSAL_INTERCEPTOR_CONFIG, useFactory: msalInterceptorConfigFactory },
    { provide: HTTP_INTERCEPTORS, useClass: MsalInterceptor, multi: true },
    MsalService,
    MsalGuard,
    MsalBroadcastService,
        provideTablerIcons({
      IconHome,
      IconDatabase,
      IconMessages,
      IconUsers,
      IconHelpCircle,
      IconLayoutSidebarLeftCollapse,
      IconLayoutSidebarLeftExpand,
      IconArrowsRightLeft,
      IconBell,
      IconInfoCircle,
      IconTerminal2,
      IconAlertTriangle,
      IconSparkles,
      IconThumbUp,
      IconThumbDown,
      IconArrowUp,
      IconArrowDown,
      IconArrowLeft,
      IconChevronRight,
      IconChevronLeft,
      IconChevronDown,
      IconCalendarMonth,
      IconBuilding,
      IconWorld,
      IconCheck,
      IconAffiliate,
      IconHourglass,
      IconTrendingUp,
      IconTrendingDown,
      IconRobot,
      IconSearch,
      IconTarget,
      IconDownload,
      IconRefresh,
      IconTag,
      IconDotsVertical,
      IconArrowDownRight,
      IconMessageReport,
      IconMessageCheck,
      IconUsersGroup,
      IconUser,
      IconBook2,
      IconArrowsMove,
      IconPlus,
      IconMinus,
      IconLibrary,
      IconChartBar,
      IconFlag,
      IconMap,
      IconFileText,
      IconReport,
      IconBriefcase,
      IconPackage,
      IconStar,
      IconStack2,
      IconChartPie,
      IconChartLine,
      IconCopy,
      IconFileExport,
      IconBulb,
      IconHandClick,
      IconCategory,
      IconX,
      IconMaximize,
      IconMessageCircle2,
      IconFileDownload,
      IconPaperclip,
      IconTriangleFilled,
      IconCircleCheck,
      IconCircleX,
      IconLanguage,
      IconLayoutGrid,
      IconArrowsShuffle,
    }),
  ]
};
